# Generated by Django 2.2.3 on 2019-08-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('content', models.CharField(max_length=10000)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
