# Generated by Django 2.2.3 on 2019-08-20 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20190819_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posst',
            options={'ordering': ['date', 'time']},
        ),
    ]
